/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ControladorUsuario;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class ModificarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ModificarUsuario
     */
    public ModificarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jTextFieldNombres = new javax.swing.JTextField();
        jLabelNombres = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelConfirmarContraseña = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelContraseñasDiferentes = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jPasswordFieldConfirmarContraseña = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setText("Modificar Datos Usuario");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 11, 164, -1));

        jLabelCedula.setText("Cédula:");
        getContentPane().add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, -1));
        getContentPane().add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        jLabelNombres.setText("Nombres:");
        getContentPane().add(jLabelNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        jTextFieldCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCedulaFocusLost(evt);
            }
        });
        getContentPane().add(jTextFieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, -1));

        jLabelNombreUsuario.setText("Nombre Usuario:");
        getContentPane().add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, -1));
        getContentPane().add(jTextFieldNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, -1));

        jLabelContraseña.setText("Contraseña");
        getContentPane().add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, -1));

        jLabelConfirmarContraseña.setText("ConfirmarContraseña: ");
        getContentPane().add(jLabelConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, -1));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jButtonCancelar.setText("Cancelar");
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));
        getContentPane().add(jLabelContraseñasDiferentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 230, -1));

        jPasswordFieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusGained(evt);
            }
        });
        getContentPane().add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, -1));

        jPasswordFieldConfirmarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldConfirmarContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldConfirmarContraseñaFocusLost(evt);
            }
        });
        getContentPane().add(jPasswordFieldConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCedulaFocusLost
        ControladorUsuario controladorUsuario = new ControladorUsuario();
        String cedula = jTextFieldCedula.getText().trim();
        boolean resultado = false;
        if (!cedula.equals("")) {
            try {
                resultado = controladorUsuario.validarUsuarioExistente(cedula, "cedula");
                if (!resultado) {
                    JOptionPane.showMessageDialog(this, "La cedula ingresada no existe", "Modificar Usuario", JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldCedula.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(CrearUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jTextFieldCedulaFocusLost

    private void jPasswordFieldConfirmarContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmarContraseñaFocusLost
        String contraseña = jPasswordFieldContraseña.getText().trim();
        String confirmarContraseña = jPasswordFieldConfirmarContraseña.getText().trim();

        if (!contraseña.equals(confirmarContraseña)) {
            jLabelContraseñasDiferentes.setText("Las contraseñas no coinciden");
            jLabelContraseñasDiferentes.setForeground(Color.red);
            //jPasswordFieldCrearUsuario.requestFocus();
        }
    }//GEN-LAST:event_jPasswordFieldConfirmarContraseñaFocusLost

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        String contraseña = jPasswordFieldContraseña.getText().trim();
        String confirmarContraseña = jPasswordFieldConfirmarContraseña.getText().trim();
        String cedula = jTextFieldCedula.getText().trim();
        String nombreUsuario = jTextFieldNombreUsuario.getText().trim().toUpperCase();
        String nombres = jTextFieldNombres.getText().toUpperCase();
        ControladorUsuario controladorUsuario = new ControladorUsuario();
        boolean resultado = false;
        boolean modificado = false;
        try {
            resultado = controladorUsuario.validarUsuarioExistente(cedula, "cedula");
        } catch (SQLException ex) {
            Logger.getLogger(ModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!contraseña.equals(confirmarContraseña)) {
            jLabelContraseñasDiferentes.setText("Las contraseñas no coinciden");
            jLabelContraseñasDiferentes.setForeground(Color.red);
            //jPasswordFieldCrearUsuario.requestFocus();
        } else if (cedula.equals("")) {
            JOptionPane.showMessageDialog(this, "El campo cédula está vacío", "Modificar Usuario", JOptionPane.INFORMATION_MESSAGE);
        } else if (!resultado) {
            JOptionPane.showMessageDialog(this, "La cedula ingresada no existe", "Crear Usuarios", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldCedula.requestFocus();
        } else {
            try {
                modificado = controladorUsuario.modificarDatosUsuario(cedula, nombreUsuario, contraseña, nombres);
                if (modificado) {
                    JOptionPane.showMessageDialog(this, "El usuario se actualizó  satiafactoriamnete", "Modificar Usuario", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Error en la actualización del Usuario", "Modificar Usuario", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ModificarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jPasswordFieldContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusGained
        jLabelContraseñasDiferentes.setText("");
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusGained

    private void jPasswordFieldConfirmarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmarContraseñaFocusGained
        jLabelContraseñasDiferentes.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfirmarContraseñaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelConfirmarContraseña;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelContraseñasDiferentes;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPasswordFieldConfirmarContraseña;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    private javax.swing.JTextField jTextFieldNombres;
    // End of variables declaration//GEN-END:variables
}
